#!/bin/bash

MIFMOG_LOCATION=~/Development/mifmog

ShowHelpPage() {
    echo "USAGE"
    echo "  mifmog new <SHEETNAME>"
    echo "  mifmog edit <SHEETNAME>"
    echo "  mifmog eval <SHEETNAME>"
    echo "  mifmog --help"
}

if [[ $# -eq 2 && "$1" == "new" ]]; then
    SHEET_NAME="$2"
    SHEET_FILEPATH="${SHEET_NAME}.yaml"
    if [ -f "$SHEET_FILEPATH" ]; then
        echo Sheet already exists && exit 1
    fi
    echo "name: \"$SHEET_NAME\"" > $SHEET_FILEPATH
    echo "desc: \"\"" >> $SHEET_FILEPATH
    cat $MIFMOG_LOCATION/res/task.yaml >> $SHEET_FILEPATH
    echo Created sheet $SHEET_FILEPATH

elif [[ $# -eq 2 && "$1" == "edit" ]]; then
    vim $2
    python3 $MIFMOG_LOCATION/main.py evaluate $2

elif [[ $# -eq 2 && "$1" == "eval" ]]; then
    python3 $MIFMOG_LOCATION/main.py evaluate $2

elif [ "$1" == "--help" ]; then
    echo "mifmog - mifmog is for managing one's goals"
    echo ""
    ShowHelpPage

else
    echo Invalid arguments
    echo ""
    ShowHelpPage

fi
